"""Intelligent Workspace Manager: turns the knowledge graph and usage history into proactive
recommendations, and manages workspaces - named groups of related files that open together.

Recommendations are rule-based over data DreamOS already holds (graph edges, open counts,
organizer state), not generated by the LLM: they are reproducible, explainable ("these files
are linked because..."), and cost no extra model calls.
"""

import re
import sqlite3
import time
from collections import Counter
from dataclasses import dataclass, field
from datetime import datetime, timezone

from app import context_memory, knowledge_graph
from app.config import settings
from app.db import connection

MAX_NAME_LENGTH = 60
SECONDS_PER_DAY = 86400

# Words dropped when matching a spoken workspace name ("open my resumes workspace").
_NAME_NOISE = {"workspace", "workspaces", "my", "the", "a", "open", "show", "launch", "start"}


@dataclass
class Recommendation:
    kind: str  # cluster | frequent | duplicate | unorganized | stale
    title: str
    detail: str
    paths: list[str] = field(default_factory=list)
    action: str | None = None  # create_workspace | organize | None (informational)
    workspace_name: str | None = None


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _pretty(label: str) -> str:
    label = label.replace("_", " ")
    return label.upper() if len(label) <= 3 else label.title()  # "cv" -> "CV", "sql" -> "SQL"


def _tokens(text: str) -> set[str]:
    return {t for t in re.findall(r"[a-z0-9]+", text.lower()) if t not in _NAME_NOISE}


def _workspace_files(conn: sqlite3.Connection, workspace_id: int) -> list[dict]:
    rows = conn.execute(
        """
        SELECT f.path, f.name FROM workspace_files w
        JOIN files f ON f.id = w.file_id
        WHERE w.workspace_id = ? ORDER BY f.name
        """,
        (workspace_id,),
    ).fetchall()
    return [
        {"path": r["path"], "name": r["name"], "abs_path": str((settings.vault_dir / r["path"]).resolve())}
        for r in rows
    ]


def create_workspace(name: str, paths: list[str], description: str | None = None) -> dict:
    name = name.strip()
    if not name or len(name) > MAX_NAME_LENGTH:
        raise ValueError(f"Workspace name must be 1-{MAX_NAME_LENGTH} characters")

    with connection() as conn:
        file_ids = []
        for path in paths:
            row = conn.execute("SELECT id FROM files WHERE path = ?", (path,)).fetchone()
            if row:
                file_ids.append(row["id"])
        if not file_ids:
            raise ValueError("None of the given paths are indexed files")

        try:
            cursor = conn.execute(
                "INSERT INTO workspaces (name, description, created_at) VALUES (?, ?, ?)",
                (name, description, _now()),
            )
        except sqlite3.IntegrityError as exc:
            raise ValueError(f"A workspace named '{name}' already exists") from exc

        workspace_id = cursor.lastrowid
        conn.executemany(
            "INSERT OR IGNORE INTO workspace_files (workspace_id, file_id) VALUES (?, ?)",
            [(workspace_id, fid) for fid in file_ids],
        )
        return {
            "id": workspace_id,
            "name": name,
            "description": description,
            "files": _workspace_files(conn, workspace_id),
        }


def list_workspaces() -> list[dict]:
    with connection() as conn:
        rows = conn.execute(
            "SELECT id, name, description FROM workspaces ORDER BY id"
        ).fetchall()
        return [
            {
                "id": r["id"],
                "name": r["name"],
                "description": r["description"],
                "files": _workspace_files(conn, r["id"]),
            }
            for r in rows
        ]


def delete_workspace(workspace_id: int) -> bool:
    with connection() as conn:
        return conn.execute("DELETE FROM workspaces WHERE id = ?", (workspace_id,)).rowcount > 0


def find_workspace(query: str) -> dict | None:
    """Finds a workspace from a spoken name: all its name's words appear in the query, or
    the query's words all appear in its name ("resumes" -> "Resumes", "my invoices workspace").
    """
    wanted = _tokens(query)
    if not wanted:
        return None
    for ws in list_workspaces():
        name_tokens = _tokens(ws["name"])
        if name_tokens and (name_tokens <= wanted or wanted <= name_tokens):
            return ws
    return None


def open_workspace(workspace_id: int) -> list[str] | None:
    """Absolute paths of a workspace's files, recording each as opened. None if it doesn't exist."""
    with connection() as conn:
        exists = conn.execute("SELECT 1 FROM workspaces WHERE id = ?", (workspace_id,)).fetchone()
        if exists is None:
            return None
        files = _workspace_files(conn, workspace_id)
    for f in files:
        context_memory.record_open(f["path"])
    return [f["abs_path"] for f in files]


# ---------------------------------------------------------------- recommendations


def _suggest_name(files: list[sqlite3.Row], taken: set[str]) -> str:
    categories = Counter(f["category"] for f in files if f["category"])
    tags = Counter(t for f in files for t in (f["tags"] or "").split(",") if t)
    if categories and categories.most_common(1)[0][1] / len(files) >= 0.6:
        base = _pretty(categories.most_common(1)[0][0])
    elif tags:
        base = _pretty(tags.most_common(1)[0][0])
    else:
        base = "Related files"

    name, n = base, 2
    while name.lower() in taken:
        name = f"{base} ({n})"
        n += 1
    return name


def _cluster_recommendations(conn: sqlite3.Connection, existing: list[dict]) -> list[Recommendation]:
    covered = [{f["path"] for f in ws["files"]} for ws in existing]
    taken = {ws["name"].lower() for ws in existing}
    recs = []
    for cluster in knowledge_graph.clusters():
        if len(cluster) > settings.workspace_max_cluster_size:
            continue
        marks = ",".join("?" * len(cluster))
        files = conn.execute(
            f"SELECT id, path, category, tags FROM files WHERE id IN ({marks})", cluster
        ).fetchall()
        paths = sorted(f["path"] for f in files)
        if any(set(paths) <= group for group in covered):
            continue  # already lives inside a workspace
        name = _suggest_name(files, taken)
        taken.add(name.lower())
        recs.append(
            Recommendation(
                kind="cluster",
                title=f"Group {len(paths)} related files into a '{name}' workspace",
                detail="These files are linked in the knowledge graph (similar content or direct references).",
                paths=paths,
                action="create_workspace",
                workspace_name=name,
            )
        )
    return recs


def _frequent_recommendations(existing: list[dict]) -> list[Recommendation]:
    counts = context_memory.open_counts()
    frequent = sorted(
        (p for p, n in counts.items() if n >= settings.frequent_open_threshold),
        key=lambda p: counts[p],
        reverse=True,
    )
    if not frequent or any(ws["name"].lower() == "frequently used" for ws in existing):
        return []
    return [
        Recommendation(
            kind="frequent",
            title=f"Keep your {len(frequent)} most-opened files one click away",
            detail="You have opened these at least "
            f"{settings.frequent_open_threshold} times: "
            + ", ".join(f"{p.rsplit('/', 1)[-1]} ({counts[p]}x)" for p in frequent[:5]),
            paths=frequent,
            action="create_workspace",
            workspace_name="Frequently used",
        )
    ]


def _duplicate_recommendations(conn: sqlite3.Connection) -> list[Recommendation]:
    rows = conn.execute(
        """
        SELECT s.path AS a, d.path AS b, e.weight, (s.content_hash = d.content_hash) AS identical
        FROM file_edges e
        JOIN files s ON s.id = e.src_id
        JOIN files d ON d.id = e.dst_id
        WHERE e.kind = 'similar' AND e.weight >= ?
        ORDER BY e.weight DESC
        """,
        (settings.graph_duplicate_threshold,),
    ).fetchall()
    return [
        Recommendation(
            kind="duplicate",
            title=f"{r['a'].rsplit('/', 1)[-1]} and {r['b'].rsplit('/', 1)[-1]} look like duplicates",
            detail="Identical content." if r["identical"] else f"{round(r['weight'] * 100)}% similar - likely two versions of one document.",
            paths=[r["a"], r["b"]],
        )
        for r in rows
    ]


def _unorganized_recommendations(conn: sqlite3.Connection) -> list[Recommendation]:
    rows = conn.execute("SELECT path FROM files WHERE category IS NULL ORDER BY path").fetchall()
    if not rows:
        return []
    return [
        Recommendation(
            kind="unorganized",
            title=f"{len(rows)} file{'s' if len(rows) != 1 else ''} not organized yet",
            detail="Ask DreamOS to organize them and review each suggestion before anything moves.",
            paths=[r["path"] for r in rows],
            action="organize",
        )
    ]


def _stale_recommendations(conn: sqlite3.Connection, now: float) -> list[Recommendation]:
    opened = context_memory.open_counts()
    cutoff = now - settings.stale_days * SECONDS_PER_DAY
    rows = conn.execute("SELECT path FROM files WHERE mtime < ? ORDER BY mtime", (cutoff,)).fetchall()
    stale = [r["path"] for r in rows if r["path"] not in opened]
    if not stale:
        return []
    return [
        Recommendation(
            kind="stale",
            title=f"{len(stale)} file{'s' if len(stale) != 1 else ''} untouched for {settings.stale_days}+ days",
            detail="Not modified and never opened through DreamOS - candidates to archive.",
            paths=stale,
        )
    ]


def recommend(now: float | None = None) -> list[Recommendation]:
    now = time.time() if now is None else now
    cap = settings.workspace_max_recommendations_per_kind
    existing = list_workspaces()
    with connection() as conn:
        groups = [
            _cluster_recommendations(conn, existing)[:cap],
            _frequent_recommendations(existing),
            _duplicate_recommendations(conn)[:cap],
            _unorganized_recommendations(conn),
            _stale_recommendations(conn, now),
        ]
    return [rec for group in groups for rec in group]
